/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vivo API
 * OpenAPI spec version: v1
 */

export interface CreateShortenedUrlRequest {
  /** @minLength 1 */
  originalUrl: string;
  /** @nullable */
  requestedExpiresAt?: string | null;
}
