/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vivo API
 * OpenAPI spec version: v1
 */

export interface ShortenedUrlResponse {
  id: string;
  /** @minLength 1 */
  code: string;
  /** @minLength 1 */
  originalUrl: string;
  /** @minLength 1 */
  shortUrl: string;
  createdAt: string;
  clickCount: number;
}
