/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vivo API
 * OpenAPI spec version: v1
 */
import { faker } from '@faker-js/faker';

import type { CreateShortenedUrlResponse, ShortenedUrlResponse } from '../model';

export const getGetRecentShortenedUrlsResponseMock = (): ShortenedUrlResponse[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.string.uuid(),
    code: faker.string.alpha({ length: { min: 1, max: 20 } }),
    originalUrl: faker.string.alpha({ length: { min: 1, max: 20 } }),
    shortUrl: faker.string.alpha({ length: { min: 1, max: 20 } }),
    createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
    clickCount: faker.number.int(),
  }));

export const getCreateAsyncResponseMock = (
  overrideResponse: Partial<Extract<CreateShortenedUrlResponse, object>> = {},
): CreateShortenedUrlResponse => ({
  shortUrl: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});
