/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vivo API
 * OpenAPI spec version: v1
 */
import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type { CreateShortenedUrlResponse, ShortenedUrlResponse } from '../model';

import {
  getCreateAsyncResponseMock,
  getGetRecentShortenedUrlsResponseMock,
} from './shortened-urls.faker';

export {
  getGetRecentShortenedUrlsResponseMock,
  getCreateAsyncResponseMock,
} from './shortened-urls.faker';

export const getGetRecentShortenedUrlsMockHandler = (
  overrideResponse?:
    | ShortenedUrlResponse[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ShortenedUrlResponse[]> | ShortenedUrlResponse[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/shortened-url',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetRecentShortenedUrlsResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getCreateAsyncMockHandler = (
  overrideResponse?:
    | CreateShortenedUrlResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<CreateShortenedUrlResponse> | CreateShortenedUrlResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/shortened-url',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getCreateAsyncResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getRedirectToOriginalMockHandler = (
  overrideResponse?:
    unknown | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/:code',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};
export const getShortenedUrlsMock = () => [
  getGetRecentShortenedUrlsMockHandler(),
  getCreateAsyncMockHandler(),
  getRedirectToOriginalMockHandler(),
];
