/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vivo API
 * OpenAPI spec version: v1
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse,
  httpResource,
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams,
  HttpResourceOptions,
  HttpResourceRef,
  HttpResourceRequest,
} from '@angular/common/http';

import { Injectable, inject } from '@angular/core';
import type { ResourceStatus, Signal } from '@angular/core';

import { Observable } from 'rxjs';

import type {
  CreateShortenedUrlRequest,
  CreateShortenedUrlResponse,
  ShortenedUrlResponse,
} from '../model';

export interface OrvalHttpResourceRequestExtension {
  /** Extra headers merged over generated headers. Pass a function to read signals reactively. */
  headers?: HttpResourceRequest['headers'] | (() => HttpResourceRequest['headers']);
  /** Angular HttpContext forwarded to the underlying request. Pass a function to derive it reactively. */
  context?: HttpContext | (() => HttpContext);
  /** Last-resort escape hatch: transform the final request descriptor. Runs inside the resource's reactive context. */
  request?: (request: HttpResourceRequest) => HttpResourceRequest;
}

export type OrvalHttpResourceOptions<
  TValue,
  TRaw = unknown,
  TOmitParse extends boolean = false,
> = (TOmitParse extends true
  ? Omit<HttpResourceOptions<TValue, TRaw>, 'parse'>
  : HttpResourceOptions<TValue, TRaw>) &
  OrvalHttpResourceRequestExtension;

function mergeOrvalResourceHeaders(
  base: HttpResourceRequest['headers'],
  extra: NonNullable<HttpResourceRequest['headers']>,
): NonNullable<HttpResourceRequest['headers']> {
  if (!base) return extra;
  if (base instanceof HttpHeaders || extra instanceof HttpHeaders) {
    const toHeaderValue = (value: string | readonly string[]): string | string[] =>
      Array.isArray(value) ? Array.from(value, String) : String(value);
    let merged =
      base instanceof HttpHeaders
        ? base
        : Object.entries(base).reduce(
            (headers, [key, value]) => headers.set(key, toHeaderValue(value)),
            new HttpHeaders(),
          );
    const extraRecord =
      extra instanceof HttpHeaders
        ? extra.keys().reduce<Record<string, string[]>>((record, key) => {
            const values = extra.getAll(key);
            if (values) record[key] = values;
            return record;
          }, {})
        : extra;
    for (const [key, value] of Object.entries(extraRecord)) {
      merged = merged.set(key, toHeaderValue(value));
    }
    return merged;
  }
  return { ...base, ...extra };
}

export function applyOrvalRequestExtension(
  request: string | HttpResourceRequest,
  options?: OrvalHttpResourceRequestExtension,
): HttpResourceRequest {
  const base: HttpResourceRequest = typeof request === 'string' ? { url: request } : request;
  if (
    !options ||
    (options.headers === undefined &&
      options.context === undefined &&
      options.request === undefined)
  ) {
    return base;
  }
  let next: HttpResourceRequest = { ...base };
  const extraHeaders = typeof options.headers === 'function' ? options.headers() : options.headers;
  if (extraHeaders) {
    next = { ...next, headers: mergeOrvalResourceHeaders(next.headers, extraHeaders) };
  }
  const context = typeof options.context === 'function' ? options.context() : options.context;
  if (context !== undefined) {
    next = { ...next, context };
  }
  return options.request ? options.request(next) : next;
}
/**
 * @remarks httpResource is available in Angular 19.2 and later.
 */
export function getRecentShortenedUrlsResource(
  options: OrvalHttpResourceOptions<ShortenedUrlResponse[], unknown> & {
    defaultValue: NoInfer<ShortenedUrlResponse[]>;
  },
): HttpResourceRef<ShortenedUrlResponse[]>;
export function getRecentShortenedUrlsResource(
  options?: OrvalHttpResourceOptions<ShortenedUrlResponse[], unknown>,
): HttpResourceRef<ShortenedUrlResponse[] | undefined>;
export function getRecentShortenedUrlsResource(
  options?: OrvalHttpResourceOptions<ShortenedUrlResponse[], unknown>,
): HttpResourceRef<ShortenedUrlResponse[] | undefined> {
  return httpResource<ShortenedUrlResponse[]>(
    () => applyOrvalRequestExtension(`http://localhost:5000/api/shortened-url`, options),
    options,
  );
}

/**
 * @remarks httpResource is available in Angular 19.2 and later.
 */
export function redirectToOriginalResource(
  code: Signal<string>,
  options: OrvalHttpResourceOptions<unknown, unknown> & { defaultValue: NoInfer<unknown> },
): HttpResourceRef<unknown>;
export function redirectToOriginalResource(
  code: Signal<string>,
  options?: OrvalHttpResourceOptions<unknown, unknown>,
): HttpResourceRef<unknown | undefined>;
export function redirectToOriginalResource(
  code: Signal<string>,
  options?: OrvalHttpResourceOptions<unknown, unknown>,
): HttpResourceRef<unknown | undefined> {
  return httpResource<unknown>(
    () => applyOrvalRequestExtension(`http://localhost:5000/${code()}`, options),
    options,
  );
}

interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
    HttpParams | Record<string, string | number | boolean | (string | number | boolean)[]>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: { includeHeaders?: string[] } | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

@Injectable({ providedIn: 'root' })
export class ShortenedUrlsService {
  private readonly http = inject(HttpClient);

  createAsync<TData = CreateShortenedUrlResponse>(
    createShortenedUrlRequest?: CreateShortenedUrlRequest,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  createAsync<TData = CreateShortenedUrlResponse>(
    createShortenedUrlRequest?: CreateShortenedUrlRequest,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  createAsync<TData = CreateShortenedUrlResponse>(
    createShortenedUrlRequest?: CreateShortenedUrlRequest,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  createAsync<TData = CreateShortenedUrlResponse>(
    createShortenedUrlRequest?: CreateShortenedUrlRequest,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
        `http://localhost:5000/api/shortened-url`,
        createShortenedUrlRequest,
        {
          ...(options as Omit<NonNullable<typeof options>, 'observe'>),
          observe: 'events',
        },
      );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
        `http://localhost:5000/api/shortened-url`,
        createShortenedUrlRequest,
        {
          ...(options as Omit<NonNullable<typeof options>, 'observe'>),
          observe: 'response',
        },
      );
    }

    return this.http.post<TData>(
      `http://localhost:5000/api/shortened-url`,
      createShortenedUrlRequest,
      {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      },
    );
  }
}

export type GetRecentShortenedUrlsResourceResult = NonNullable<ShortenedUrlResponse[]>;
export type RedirectToOriginalResourceResult = NonNullable<unknown>;

/**
 * Utility type for httpResource results with status tracking.
 * Inspired by @angular-architects/ngrx-toolkit withResource pattern.
 *
 * Uses `globalThis.Error` to avoid collision with API model types named `Error`.
 */
export interface ResourceState<T> {
  readonly value: Signal<T | undefined>;
  readonly status: Signal<ResourceStatus>;
  readonly error: Signal<globalThis.Error | undefined>;
  readonly isLoading: Signal<boolean>;
  /** Guard reads of `value()` with this call: `value()` throws in the error state. */
  readonly hasValue: () => this is ResolvedResourceState<T>;
  readonly reload: () => boolean;
}

export interface ResolvedResourceState<T> extends ResourceState<T> {
  readonly value: Signal<Exclude<T, undefined>>;
}

/**
 * Wraps an HttpResourceRef to expose a consistent ResourceState interface.
 * Useful when integrating with NgRx SignalStore via withResource().
 */
export function toResourceState<T>(ref: HttpResourceRef<T>): ResourceState<T> {
  return {
    value: ref.value,
    status: ref.status,
    error: ref.error,
    isLoading: ref.isLoading,
    hasValue(this: ResourceState<T>): this is ResolvedResourceState<T> {
      return ref.hasValue();
    },
    reload: () => ref.reload(),
  };
}
